import { Router } from "express";
import authRoutes from "./authRoutes";
import userRoutes from "./userRoutes";
import projectRoutes from "./projectRoutes";
import timesheetRoutes from "./timesheetRoutes";
import timerRoutes from "./timerRoutes";
import reportRoutes from "./reportRoutes";
import attendanceRoutes from "./attendanceRoutes";
import leaveRoutes from "./leaveRoutes";
import documentRoutes from "./documentRoutes";
import employeeProfileRoutes from "./employeeProfileRoutes";
import holidayRoutes from "./holidayRoutes";
import wfhRoutes from "./wfhRoutes";
import compOffRoutes from "./compOffRoutes";
import weeklyTimesheetRoutes from "./weeklyTimesheetRoutes";
import dashboardRoutes from "./dashboardRoutes";
import announcementRoutes from "./announcementRoutes";
import recognitionRoutes from "./recognitionRoutes";
import surveyRoutes from "./surveyRoutes";
import adminSettingsRoutes from "./adminSettingsRoutes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/projects", projectRoutes);
router.use("/timesheets", timesheetRoutes);
router.use("/timers", timerRoutes);
router.use("/reports", reportRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/leaves", leaveRoutes);
router.use("/documents", documentRoutes);
router.use("/employee-profile", employeeProfileRoutes);
router.use("/holidays", holidayRoutes);
router.use("/wfh", wfhRoutes);
router.use("/compoff", compOffRoutes);
router.use("/weekly-timesheet", weeklyTimesheetRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/announcements", announcementRoutes);
router.use("/recognition", recognitionRoutes);
router.use("/surveys", surveyRoutes);
router.use("/admin/settings", adminSettingsRoutes);

export default router;
